<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_fullname_fullname</name>
   <tag></tag>
   <elementGuidId>d595aefd-81e3-45cf-9a8a-67881fa54eb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;username&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/form/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>username border-[1px] py-4 px-14 rounded-[10px] border-[#D9D9D9] focus:outline-none w-full h-[62px] placeholder:text-[20px] placeholder:leading-[30px] placeholder:capitalize</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>username</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;bg-[url('/src/assets/img/Vector.png')] bg-no-repeat bg-[length:600px_584px]&quot;]/header[1]/div[1]/div[@class=&quot;relative&quot;]/div[@class=&quot;flex w-full bg-transparent grid grid-cols-3&quot;]/div[3]/div[1]/div[1]/div[1]/div[@class=&quot;flex items-center justify-center&quot;]/div[@class=&quot;max-w-[1000px] w-4/5 max-h-[800px] mb-8 flex flex-col items-center justify-center bg-[#fff] rounded-[30px]&quot;]/form[@class=&quot;max-w-[640px] w-4/5 flex flex-col items-center&quot;]/div[@class=&quot;w-full mb-8&quot;]/div[@class=&quot;flex items-center relative&quot;]/input[@class=&quot;username border-[1px] py-4 px-14 rounded-[10px] border-[#D9D9D9] focus:outline-none w-full h-[62px] placeholder:text-[20px] placeholder:leading-[30px] placeholder:capitalize&quot;]</value>
   </webElementProperties>
</WebElementEntity>
